Remove debug command(s) that aren't a thing anymore
lucko/LuckPerms pull request #2725
Opened 2020-11-15 13:02 UTC by powercasgamer

2020-11-17 11:04 UTC, lucko requested changes
Looks good!

2020-11-17 11:04 UTC, lucko commented on common/src/main/java/me/lucko/luckperms/common/command/access/CommandPermission.java
> +    //DEBUG("debug", Type.NONE), // Intellij says that this doesn't have any usages. Haven't fully removed it incase it is needed.
You can go ahead and remove this

2020-11-17 11:04 UTC, lucko commented on common/src/main/java/me/lucko/luckperms/common/command/spec/CommandSpec.java
> +    //DEBUG("/%s debug"), // also commented this incase it is needed, if it's not needed it'll fully remove it.
You can go ahead and remove this

2020-11-17 12:14 UTC, powercasgamer commented on common/src/main/java/me/lucko/luckperms/common/command/spec/CommandSpec.java
> +    //DEBUG("/%s debug"), // also commented this incase it is needed, if it's not needed it'll fully remove it.
Alright, will do once I'm home.

2020-11-17 16:18 UTC, powercasgamer commented
done

2020-11-18 23:52 UTC, lucko approved these changes

2020-11-18 23:52 UTC, merged