Updated to Gradle 7
lucko/LuckPerms pull request #3051
Opened 2021-06-04 14:33 UTC by BomBardyGamer

Does what it says in the title. I've also update shadow to go with this, and also switched every `compile` to `implementation` (since `compile` has been removed in 7), and switched to using `filter` to replace tokens in resource files, rather than the previously used `expand`.

2021-06-10 20:17 UTC, lucko commented
Thanks for this - I will merge once I have a spare moment to ensure Jenkins is up-to-date and configure a different Gradle install

2021-07-23 20:06 UTC, lucko commented
> switched to using filter to replace tokens in resource files, rather than the previously used expand.

Why was this, out of interest? @BomBardyGamer

2021-07-23 20:07 UTC, lucko commented
Other than that, looks good, Jenkins is ready for Java 16 + Gradle 7 so I can merge now 😄

2021-07-29 05:21 UTC, emilyy-dev requested changes

2021-07-29 05:21 UTC, emilyy-dev commented on bukkit-legacy/build.gradle
> +    archiveName 'luckperms-bukkitlegacy.jarinjar'
Seeing that the gradle scripts are being reworked, this should be `archiveFileName` (same for the other cases); `get/setArchiveName` is deprecated

2021-08-20 17:16 UTC, merged

2021-08-20 17:47 UTC, lucko commented
Thanks :)